import {
  Building2,
  CreditCard,
  FileDown,
  FileText,
  KeyRound,
  Languages,
  Mail,
  Percent,
  Receipt,
  Settings,
  SlidersHorizontal,
} from "lucide-react";

export const SETTINGS_SECTIONS = [
  {
    category: "general",
    title: "General",
    shortTitle: "General",
    description: "Regional formatting, date/time formats, default currency, and fiscal year.",
    icon: Settings,
    badge: "Core",
    color: "bg-indigo-50 text-indigo-600 dark:bg-indigo-500/10 dark:text-indigo-400 border-indigo-100 dark:border-indigo-500/20",
    hoverBg: "hover:bg-indigo-50 dark:hover:bg-indigo-500/20",
    accent: "indigo",
  },
  {
    category: "business",
    title: "Business Profile",
    shortTitle: "Business",
    description: "Company branding, contact info, office address, and GSTIN registration.",
    icon: Building2,
    badge: "Identity",
    color: "bg-blue-50 text-blue-600 dark:bg-blue-500/10 dark:text-blue-400 border-blue-100 dark:border-blue-500/20",
    hoverBg: "hover:bg-blue-50 dark:hover:bg-blue-500/20",
    accent: "blue",
  },
  {
    category: "tax",
    title: "Tax & GST",
    shortTitle: "Tax & GST",
    description: "Automated GST calculation, CGST, SGST, IGST, and tax-inclusive pricing.",
    icon: Percent,
    badge: "Billing",
    color: "bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-400 border-emerald-100 dark:border-emerald-500/20",
    hoverBg: "hover:bg-emerald-50 dark:hover:bg-emerald-500/20",
    accent: "emerald",
  },
  {
    category: "payments",
    title: "Payment Gateways",
    shortTitle: "Payments",
    description: "Razorpay live keys, direct UPI QR codes, bank accounts, and cash settlement.",
    icon: CreditCard,
    badge: "Gateways",
    color: "bg-violet-50 text-violet-600 dark:bg-violet-500/10 dark:text-violet-400 border-violet-100 dark:border-violet-500/20",
    hoverBg: "hover:bg-violet-50 dark:hover:bg-violet-500/20",
    accent: "violet",
  },
  {
    category: "invoice",
    title: "Invoice Rules",
    shortTitle: "Invoices",
    description: "Custom invoice prefixes, auto-sequence numbers, payment due days, and terms.",
    icon: Receipt,
    badge: "Invoicing",
    color: "bg-amber-50 text-amber-600 dark:bg-amber-500/10 dark:text-amber-400 border-amber-100 dark:border-amber-500/20",
    hoverBg: "hover:bg-amber-50 dark:hover:bg-amber-500/20",
    accent: "amber",
  },
  {
    category: "quotation",
    title: "Quotation Rules",
    shortTitle: "Quotes",
    description: "Estimate prefix, proposal validity periods, and default scope statements.",
    icon: FileText,
    badge: "Estimates",
    color: "bg-teal-50 text-teal-600 dark:bg-teal-500/10 dark:text-teal-400 border-teal-100 dark:border-teal-500/20",
    hoverBg: "hover:bg-teal-50 dark:hover:bg-teal-500/20",
    accent: "teal",
  },
  {
    category: "emails",
    title: "Email & SMTP",
    shortTitle: "Emails",
    description: "Outbound SMTP server host, authentication, custom sender email, and display name.",
    icon: Mail,
    badge: "Mail",
    color: "bg-pink-50 text-pink-600 dark:bg-pink-500/10 dark:text-pink-400 border-pink-100 dark:border-pink-500/20",
    hoverBg: "hover:bg-pink-50 dark:hover:bg-pink-500/20",
    accent: "pink",
  },
  {
    category: "pdf",
    title: "PDF Customizer",
    shortTitle: "PDF",
    description: "Paper sizes (A4 / Letter), primary accent brand colors, and PDF headers.",
    icon: FileDown,
    badge: "Layout",
    color: "bg-rose-50 text-rose-600 dark:bg-rose-500/10 dark:text-rose-400 border-rose-100 dark:border-rose-500/20",
    hoverBg: "hover:bg-rose-50 dark:hover:bg-rose-500/20",
    accent: "rose",
  },
  {
    category: "translate",
    title: "Localization",
    shortTitle: "Languages",
    description: "Language selection (English, Hindi, Telugu) and interface translation strings.",
    icon: Languages,
    badge: "Locale",
    color: "bg-cyan-50 text-cyan-600 dark:bg-cyan-500/10 dark:text-cyan-400 border-cyan-100 dark:border-cyan-500/20",
    hoverBg: "hover:bg-cyan-50 dark:hover:bg-cyan-500/20",
    accent: "cyan",
  },
  {
    category: "extras",
    title: "System Extras",
    shortTitle: "System",
    description: "Default dark theme settings, maintenance flags, and analytics triggers.",
    icon: SlidersHorizontal,
    badge: "System",
    color: "bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300 border-slate-200 dark:border-slate-700",
    hoverBg: "hover:bg-slate-100 dark:hover:bg-slate-800",
    accent: "slate",
  },
  {
    category: "license",
    title: "License & Tier",
    shortTitle: "License",
    description: "Workspace license verification, system build version, and active features.",
    icon: KeyRound,
    badge: "Active",
    color: "bg-purple-50 text-purple-600 dark:bg-purple-500/10 dark:text-purple-400 border-purple-100 dark:border-purple-500/20",
    hoverBg: "hover:bg-purple-50 dark:hover:bg-purple-500/20",
    accent: "purple",
  },
];
